name: zzzProvisionTest

on:
  push:
    paths:
      - ".github/workflows/provision_test.yml"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - run: powershell -Command cp C:\GHTools\powrprof_gosafe.dll C:\ActionRunner\_work\webrtc-nightly\webrtc-nightly\scripts\..\depot_tools\powrprof.dll
    # Try to build using powershell (it will take a while)
    - name: Build (win amd64)
      run: powershell  .\scripts\build.ps1
    - run: echo done2
